create extension if not exists pgcrypto;

create table if not exists public.demo_requests (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  company text not null,
  email text not null,
  role text,
  message text,
  source text,
  page_url text,
  session_id text,
  user_agent text,
  ip_hash_source text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create index if not exists demo_requests_created_at_idx
  on public.demo_requests (created_at desc);

create index if not exists demo_requests_email_idx
  on public.demo_requests (email);

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  path text,
  session_id text,
  metadata jsonb not null default '{}'::jsonb,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists site_events_created_at_idx
  on public.site_events (created_at desc);

create index if not exists site_events_event_name_idx
  on public.site_events (event_name);

alter table public.demo_requests enable row level security;
alter table public.site_events enable row level security;

revoke all on public.demo_requests from anon, authenticated;
revoke all on public.site_events from anon, authenticated;
